name: KrassAlla
version: '${project.version}'
main: de.verilyzed.krassalla.KrassAlla
api-version: 1.17
authors: [Colin, Thies, Jost]
commands:
  test:
    usage: /test
  buy:
    usage: /buy
  echo:
    usage: /echo
  backpack:
    usage: /backpack
  json:
    usage: /json
  money:
    usage: /money